In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_excel('IndianFoodDatasetXLS.xlsx')
url_list = df['URL'].tolist()
recipename = df['TranslatedRecipeName'].tolist()
print(url_list)
print(recipename)

['https://www.archanaskitchen.com/masala-karela-recipe', 'http://www.archanaskitchen.com/spicy-tomato-rice-recipe-in-hindi', 'http://www.archanaskitchen.com/ragi-vermicelli-semiya-recipe-healthy-finger-millet-semiya-breakfast', 'http://www.archanaskitchen.com/gongura-chicken-curry-recipe-andhra-style-gongura-chicken', 'https://www.archanaskitchen.com/andhra-style-allam-pachadi-ginger-chutney-recipe-in-hindi', 'http://www.archanaskitchen.com/pudina-khara-pongal-recipe-rice-and-lentils-cooked-with-mint-leaves-mild-spices', 'http://www.archanaskitchen.com/udupi-style-ash-gourd-coconut-curry-recipe', 'https://www.archanaskitchen.com/black-bean-burrito-recipe', 'http://www.archanaskitchen.com/spicy-crunchy-masala-idli-recipe', 'http://www.archanaskitchen.com/cauliflower-leaves-chutney-recipe-in-hindi', 'https://www.archanaskitchen.com/homemade-baked-beans-recipe-wholesome-healthy', 'https://www.archanaskitchen.com/veg-chili-cheese-burgers-recipe', 'https://www.archanaskitchen.com/andhra-sty

In [4]:
def download_image(url, folder_path, recipe_name):
    try:
        response = requests.get(url, stream=True)
        response.raise_for_status()

        image_name = f"{recipe_name}.jpg"

  
        image_path = os.path.join(folder_path, image_name)

      
        with open(image_path, 'wb') as image_file:
            for chunk in response.iter_content(chunk_size=8192):
                image_file.write(chunk)

        print(f"Image for '{recipe_name}' downloaded and saved successfully: {image_path}")
        return image_path

    except Exception as e:
        print(f"Error downloading image for '{recipe_name}': {e}")
        return None

def scrape_recipe_images(excel_file_path):
   
    df = pd.read_excel(excel_file_path)

    
    folder_path = "Images Data"
    os.makedirs(folder_path, exist_ok=True)

    
    for index, row in df.iterrows():
        recipe_name = row['TranslatedRecipeName']
        recipe_url = row['URL']

        try:
            response = requests.get(recipe_url)
            response.raise_for_status()

            soup = BeautifulSoup(response.content, 'html.parser')

            
            img_tag = soup.find('meta', property='og:image')

            
            img_url = img_tag['content'] if img_tag and 'content' in img_tag.attrs else None

            if img_url:
                
                download_image(img_url, folder_path, recipe_name)
            else:
                print(f"Image not found for '{recipe_name}'.")

        except Exception as e:
            print(f"Error processing '{recipe_name}': {e}")


scrape_recipe_images('IndianFoodDatasetXLS.xlsx')


Image for 'Masala Karela Recipe' downloaded and saved successfully: Images Data\Masala Karela Recipe.jpg
Image for 'Spicy Tomato Rice (Recipe)' downloaded and saved successfully: Images Data\Spicy Tomato Rice (Recipe).jpg
Image for 'Ragi Semiya Upma Recipe - Ragi Millet Vermicelli Breakfast' downloaded and saved successfully: Images Data\Ragi Semiya Upma Recipe - Ragi Millet Vermicelli Breakfast.jpg
Image for 'Gongura Chicken Curry Recipe - Andhra Style Gongura Chicken' downloaded and saved successfully: Images Data\Gongura Chicken Curry Recipe - Andhra Style Gongura Chicken.jpg
Image for 'Andhra Style Alam Pachadi Recipe - Adrak Chutney (Recipe)' downloaded and saved successfully: Images Data\Andhra Style Alam Pachadi Recipe - Adrak Chutney (Recipe).jpg
Image for 'Pudina Khara Pongal Recipe (Rice and Lentils Cooked With Mint Leaves & Mild Spices)' downloaded and saved successfully: Images Data\Pudina Khara Pongal Recipe (Rice and Lentils Cooked With Mint Leaves & Mild Spices).jpg
Imag

In [3]:
df1 = pd.read_excel('IndianFoodDatasetXLSupdated.xlsx')
df1.head()


RecipeName  \
0                               Masala Karela Recipe   
1                         Spicy Tomato Rice (Recipe)   
2  Ragi Semiya Upma Recipe - Ragi Millet Vermicel...   
3  Gongura Chicken Curry Recipe - Andhra Style Go...   
4  Andhra Style Alam Pachadi Recipe - Adrak Chutn...   

                                         Ingredients  PrepTimeInMins  \
0  6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...              15   
1  2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...               5   
2  1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...              20   
3  500 grams Chicken,2 Onion - chopped,1 Tomato -...              15   
4  1 tablespoon chana dal, 1 tablespoon white ura...              10   

   CookTimeInMins  TotalTimeInMins  Servings               Cuisine  \
0              30               45         6                Indian   
1              10               15         3  South Indian Recipes   
2              30               50         4  South Indian Recipes   
3              30               45         4                Andhra   
4              20               30         4                Andhra   

                   Course                     Diet  \
0               Side Dish        Diabetic Friendly   
1             Main Course               Vegetarian   
2  South Indian Breakfast  High Protein Vegetarian   
3                   Lunch           Non Vegeterian   
4  South Indian Breakfast               Vegetarian   

                                        Instructions  
0  To begin making the Masala Karela Recipe,de-se...  
1  To make tomato puliogere, first cut the tomato...  
2  To begin making the Ragi Vermicelli Recipe, fi...  
3  To begin making Gongura Chicken Curry Recipe f...  
4  To make Andhra Style Alam Pachadi, first heat ...

In [4]:
df1.shape

(6870, 10)

In [5]:
df1.isnull().sum()

RecipeName         0
Ingredients        6
PrepTimeInMins     0
CookTimeInMins     0
TotalTimeInMins    0
Servings           0
Cuisine            0
Course             0
Diet               0
Instructions       0
dtype: int64

In [6]:
df2 = df1.dropna()
df2.isnull().sum()


RecipeName         0
Ingredients        0
PrepTimeInMins     0
CookTimeInMins     0
TotalTimeInMins    0
Servings           0
Cuisine            0
Course             0
Diet               0
Instructions       0
dtype: int64

In [7]:
df2['TotalTimeInMins'].unique()

array([  45,   15,   50,   30,   40,   25,  120,   55,   20,   35,   60,
         65,   90,   10,   70,   75,   51,   80,  135,  100,  180,  160,
        540,   63,  380,  600,   85,   18,  110,  265,  205,  150,  360,
        495,  175,  440,  220,  230,  190,  410,  370,    5,   12,  550,
        200,  130,  105,  235,  300,  290,  155,   32,   22,  165,   46,
        280,  140,  510,  620,  250,  530, 1470,  145,  270,   95,  960,
        430,  390,  330,  610,  545,    7,  420,  320,  480,   17,  315,
         47,  460,   24,  195,  215,  225,   28,   44,   42,  800,  570,
        405,  580,  170,  435,  375,   48,   16,   71,   27,  500,  525,
        630,  305,  520,   76,   68,  260,    0,  515,   52,  149,   11,
        185,  445,   73,  539,  765,  400,  115,  980,   62,  210,  255,
        240,  125,    4,   54,  335,   29,  560,  565,  340,   13,   79,
         67,  795,  455,  285,   89,  850,  258,   53,  425, 2925,  350,
        470,  535,   69,  365,   38,  505,  740,  9

In [8]:
df3 = df2[df2['TotalTimeInMins'] <= 200]
df3.head()


RecipeName  \
0                               Masala Karela Recipe   
1                         Spicy Tomato Rice (Recipe)   
2  Ragi Semiya Upma Recipe - Ragi Millet Vermicel...   
3  Gongura Chicken Curry Recipe - Andhra Style Go...   
4  Andhra Style Alam Pachadi Recipe - Adrak Chutn...   

                                         Ingredients  PrepTimeInMins  \
0  6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...              15   
1  2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...               5   
2  1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...              20   
3  500 grams Chicken,2 Onion - chopped,1 Tomato -...              15   
4  1 tablespoon chana dal, 1 tablespoon white ura...              10   

   CookTimeInMins  TotalTimeInMins  Servings               Cuisine  \
0              30               45         6                Indian   
1              10               15         3  South Indian Recipes   
2              30               50         4  South Indian Recipes   
3              30               45         4                Andhra   
4              20               30         4                Andhra   

                   Course                     Diet  \
0               Side Dish        Diabetic Friendly   
1             Main Course               Vegetarian   
2  South Indian Breakfast  High Protein Vegetarian   
3                   Lunch           Non Vegeterian   
4  South Indian Breakfast               Vegetarian   

                                        Instructions  
0  To begin making the Masala Karela Recipe,de-se...  
1  To make tomato puliogere, first cut the tomato...  
2  To begin making the Ragi Vermicelli Recipe, fi...  
3  To begin making Gongura Chicken Curry Recipe f...  
4  To make Andhra Style Alam Pachadi, first heat ...

In [9]:
df3['TotalTimeInMins'].unique()

array([ 45,  15,  50,  30,  40,  25, 120,  55,  20,  35,  60,  65,  90,
        10,  70,  75,  51,  80, 135, 100, 180, 160,  63,  85,  18, 110,
       150, 175, 190,   5,  12, 200, 130, 105, 155,  32,  22, 165,  46,
       140, 145,  95,   7,  17,  47,  24, 195,  28,  44,  42, 170,  48,
        16,  71,  27,  76,  68,   0,  52, 149,  11, 185,  73, 115,  62,
       125,   4,  54,  29,  13,  79,  67,  89,  53,  69,  38,  37,  31,
        34,  58], dtype=int64)

In [10]:
df3['CookTimeInMins'].unique()

array([ 30,  10,  20,  60,  45,  15,  25,  35,   0,  75,  40,   5,  55,
        26, 120, 150,   8,  50,  90,  70, 190,   7,  21,  80,  65, 100,
        85,  12,  14,  18, 180,   1,  17, 160,  16, 140,   6,  32,   2,
        24,  19,  34,   3, 110,  28,   4,  38], dtype=int64)

In [11]:
df3['PrepTimeInMins'].unique()

array([ 15,   5,  20,  10,  60,   0,  30,  45,  25,  50, 120,  90, 150,
        40,  38,  65,  35, 135,  75, 180,   2,  70, 130, 140,  16, 110,
         7,  21,  12, 100,   4,  55,  18,  26, 105,  80,  48, 119,  33,
        31,  34,  37,  19,  23,  14,   8,   6,  11,   1], dtype=int64)

In [16]:
df4 = df3[df3['TotalTimeInMins'] <= 150]
df4.head()

RecipeName  \
0                               Masala Karela Recipe   
1                         Spicy Tomato Rice (Recipe)   
2  Ragi Semiya Upma Recipe - Ragi Millet Vermicel...   
3  Gongura Chicken Curry Recipe - Andhra Style Go...   
4  Andhra Style Alam Pachadi Recipe - Adrak Chutn...   

                                         Ingredients  PrepTimeInMins  \
0  6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...              15   
1  2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...               5   
2  1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...              20   
3  500 grams Chicken,2 Onion - chopped,1 Tomato -...              15   
4  1 tablespoon chana dal, 1 tablespoon white ura...              10   

   CookTimeInMins  TotalTimeInMins  Servings               Cuisine  \
0              30               45         6                Indian   
1              10               15         3  South Indian Recipes   
2              30               50         4  South Indian Recipes   
3              30               45         4                Andhra   
4              20               30         4                Andhra   

                   Course                     Diet  \
0               Side Dish        Diabetic Friendly   
1             Main Course               Vegetarian   
2  South Indian Breakfast  High Protein Vegetarian   
3                   Lunch           Non Vegeterian   
4  South Indian Breakfast               Vegetarian   

                                        Instructions  
0  To begin making the Masala Karela Recipe,de-se...  
1  To make tomato puliogere, first cut the tomato...  
2  To begin making the Ragi Vermicelli Recipe, fi...  
3  To begin making Gongura Chicken Curry Recipe f...  
4  To make Andhra Style Alam Pachadi, first heat ...

In [17]:
df4['Servings'].unique()

array([  6,   3,   4,   2,   8,  10,  30,   1,  12,   9,  20,   5,  80,
       100,  15,  16,  40, 300, 500,   7, 200,  25,  14, 250,  35,  24,
       400, 150,  18, 240, 600], dtype=int64)

In [19]:
df5 = df4[df4['Servings'] <= 10]
df5.head()

RecipeName  \
0                               Masala Karela Recipe   
1                         Spicy Tomato Rice (Recipe)   
2  Ragi Semiya Upma Recipe - Ragi Millet Vermicel...   
3  Gongura Chicken Curry Recipe - Andhra Style Go...   
4  Andhra Style Alam Pachadi Recipe - Adrak Chutn...   

                                         Ingredients  PrepTimeInMins  \
0  6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...              15   
1  2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...               5   
2  1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...              20   
3  500 grams Chicken,2 Onion - chopped,1 Tomato -...              15   
4  1 tablespoon chana dal, 1 tablespoon white ura...              10   

   CookTimeInMins  TotalTimeInMins  Servings               Cuisine  \
0              30               45         6                Indian   
1              10               15         3  South Indian Recipes   
2              30               50         4  South Indian Recipes   
3              30               45         4                Andhra   
4              20               30         4                Andhra   

                   Course                     Diet  \
0               Side Dish        Diabetic Friendly   
1             Main Course               Vegetarian   
2  South Indian Breakfast  High Protein Vegetarian   
3                   Lunch           Non Vegeterian   
4  South Indian Breakfast               Vegetarian   

                                        Instructions  
0  To begin making the Masala Karela Recipe,de-se...  
1  To make tomato puliogere, first cut the tomato...  
2  To begin making the Ragi Vermicelli Recipe, fi...  
3  To begin making Gongura Chicken Curry Recipe f...  
4  To make Andhra Style Alam Pachadi, first heat ...

In [20]:
df5.to_excel("Final_data.xlsx", index=False)